"""Storage contracts for swapping local SQLite for production backends."""

from __future__ import annotations

from typing import Any, Protocol

from .models import MemoryRecord, MemoryWriteResult


class MemoryRepository(Protocol):
    def upsert(self, record: MemoryRecord) -> MemoryWriteResult: ...
    def get(self, memory_id: str) -> MemoryRecord | None: ...
    def list(self, *, namespace: str, memory_type: str | None = None, active_only: bool = True, limit: int = 100) -> list[MemoryRecord]: ...
    def candidates(self, *, namespace: str, memory_types: list[str], schema_hash: str, limit: int = 1000) -> list[MemoryRecord]: ...
    def set_memory_active(self, memory_id: str, active: bool) -> None: ...
    def update_memory_metadata(self, memory_id: str, metadata: dict[str, Any]) -> None: ...

